export default {
    coins: [
        "bitcoin",
        "ethereum",
        "tether",
        "cardano",
        "ripple",
        "dogecoin",
        "solana",
        "litecoin",
        "matic-network",
        "terra-luna",
        "binancecoin",
        "polkadot",
        "01coin",
        "usd-coin",
        "avalanche-2",
        "cosmos",
        "stellar",
        "pancakeswap-token",
    ],
};
